<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Brand::insert([
             ['name'=> 'Ani',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Bacanix',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Candies Supplier',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Chispuditos',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Crismelos',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Delicia',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Dragon',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Favora',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
             ['name'=> 'Felpa',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name' => 'Franelita',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Gato Negro',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
             ['name'=> 'Guandy',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Lo-Zano',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Nissin',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Olat',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Pa Picar',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
             ['name'=> 'PomPom',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'SabroCronchis',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
             ['name'=> 'Sensations',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Tentacion',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],
            ['name'=> 'Tropi-Kuhl',
             'description' => '',
             'Status' => 1,
             'created_at'=> now(),
            ],

        ]);
    }
}
